//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hastaportali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktorlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doktorlar()
        {
            this.HastaBilgi = new HashSet<HastaBilgi>();
            this.HastaKayit1 = new HashSet<HastaKayit>();
            this.kayitlar = new HashSet<kayitlar>();
            this.Randevu1 = new HashSet<Randevu>();
            this.Recete = new HashSet<Recete>();
            this.TahlilSonuc = new HashSet<TahlilSonuc>();
            this.Tipdallari1 = new HashSet<Tipdallari>();
        }
    
        public string DoktorKimlik { get; set; }
        public string DoktorAdSoyad { get; set; }
        public string DoktorTel { get; set; }
        public string DoktorE_mail { get; set; }
        public string DoktorTipDaliId { get; set; }
        public string DoktorFoto { get; set; }
        public string DoktorSifre { get; set; }
        public string TedaviAlanlarKimlik { get; set; }
        public string randevular { get; set; }
        public Nullable<int> DoktorAdmin { get; set; }
    
        public virtual HastaKayit HastaKayit { get; set; }
        public virtual Randevu Randevu { get; set; }
        public virtual Tipdallari Tipdallari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaBilgi> HastaBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaKayit> HastaKayit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kayitlar> kayitlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recete> Recete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TahlilSonuc> TahlilSonuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipdallari> Tipdallari1 { get; set; }
    }
}
