//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hastaportali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HastaBilgi()
        {
            this.HastaKayit1 = new HashSet<HastaKayit>();
        }
    
        public string HastaBilgiId { get; set; }
        public string Yas { get; set; }
        public string Uzunluk { get; set; }
        public string Agarlik { get; set; }
        public string KanGrubu { get; set; }
        public string Tansiyon { get; set; }
        public string Nabiz { get; set; }
        public string SolunumSayisi { get; set; }
        public string Sicaklik { get; set; }
        public string Diyet { get; set; }
        public string Alerji { get; set; }
        public System.DateTime OlcmeTarihi { get; set; }
        public string OlcmeYapanDoktorKimlik { get; set; }
        public string E_imza { get; set; }
        public string bilgiaitHastaKimlik { get; set; }
    
        public virtual Doktorlar Doktorlar { get; set; }
        public virtual HastaKayit HastaKayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaKayit> HastaKayit1 { get; set; }
    }
}
