//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hastaportali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayitlar
    {
        public string kayitId { get; set; }
        public string kayitdoktorkimlik { get; set; }
        public string kayithastakimlik { get; set; }
    
        public virtual Doktorlar Doktorlar { get; set; }
        public virtual HastaKayit HastaKayit { get; set; }
    }
}
