//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hastaportali.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db01Entities13 : DbContext
    {
        public db01Entities13()
            : base("name=db01Entities13")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doktorlar> Doktorlar { get; set; }
        public virtual DbSet<HastaBilgi> HastaBilgi { get; set; }
        public virtual DbSet<HastaKayit> HastaKayit { get; set; }
        public virtual DbSet<kayitlar> kayitlar { get; set; }
        public virtual DbSet<Randevu> Randevu { get; set; }
        public virtual DbSet<Recete> Recete { get; set; }
        public virtual DbSet<TahlilSonuc> TahlilSonuc { get; set; }
        public virtual DbSet<Tipdallari> Tipdallari { get; set; }
    }
}
