//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hastaportali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Randevu()
        {
            this.Doktorlar = new HashSet<Doktorlar>();
        }
    
        public string RandevuId { get; set; }
        public System.TimeSpan RandevuSaati { get; set; }
        public System.DateTime RandevuTarihi { get; set; }
        public string RandevuDoktorKimlik { get; set; }
        public string Randevuhastakayit { get; set; }
        public string RandevuTipDaliId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doktorlar> Doktorlar { get; set; }
        public virtual Doktorlar Doktorlar1 { get; set; }
        public virtual HastaKayit HastaKayit { get; set; }
        public virtual Tipdallari Tipdallari { get; set; }
    }
}
