//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hastaportali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recete
    {
        public string ReceteId { get; set; }
        public string IlacAdi { get; set; }
        public string Miktarlar { get; set; }
        public string Doz { get; set; }
        public string Sure { get; set; }
        public System.DateTime ReceteTarih { get; set; }
        public string E_imza { get; set; }
        public string Recetehastakayit { get; set; }
        public string Recetedoktorkimlik { get; set; }
    
        public virtual Doktorlar Doktorlar { get; set; }
        public virtual HastaKayit HastaKayit { get; set; }
    }
}
